FLO_StoreDialogIdd = 9800;
FLO_StoreBrowserIdc = 9801;
FLO_StoreActiveFobNetId = "";
FLO_StoreClientPendingVehicles = [];
FLO_StorePurchasedVehicleKilledEh = -1;
FLO_StorePlaceableMagazineCache = createHashMap;
FLO_StorePlaceableMagazineCacheReady = false;
FLO_StoreDeploymentFundAmount = 1000;
FLO_StoreDeploymentFundMaxItemPrice = 650;
FLO_StoreDeploymentFundCategories = [
    "primary",
    "handgun",
    "uniforms",
    "vests",
    "headgear",
    "facewear",
    "backpacks",
    "attachments",
    "ammo",
    "misc"
];

FLO_StoreCategories = [
    ["primary", "Primary"],
    ["handgun", "Handgun"],
    ["secondary", "Launchers"],
    ["uniforms", "Uniforms"],
    ["vests", "Vests"],
    ["headgear", "Headgear"],
    ["facewear", "Facewear"],
    ["backpacks", "Backpacks"],
    ["attachments", "Attachments"],
    ["ammo", "Ammo"],
    ["mines", "Mines"],
    ["misc", "Items"],
    ["tickets", "Tickets"],
    ["cars", "Cars"],
    ["armor", "Armor"],
    ["helis", "Helicopters"],
    ["planes", "Planes"],
    ["naval", "Naval"],
    ["static", "Statics"],
    ["other", "Other"]
];

FLO_StoreGearCategories = [
    "primary",
    "handgun",
    "secondary",
    "uniforms",
    "vests",
    "headgear",
    "facewear",
    "backpacks",
    "attachments",
    "ammo",
    "mines",
    "misc"
];

FLO_StoreVehicleCategories = [
    "cars",
    "armor",
    "helis",
    "planes",
    "naval",
    "static",
    "other"
];

FLO_StoreGearContainers = [
    "auto",
    "uniform",
    "vest",
    "backpack"
];

FLO_StoreTicketPacks = [
    ["foof_ticket_5", "Reinforcement Tickets x5", 5, 450],
    ["foof_ticket_10", "Reinforcement Tickets x10", 10, 850],
    ["foof_ticket_25", "Reinforcement Tickets x25", 25, 1900]
];

FLO_StoreSupportModSources = [
    ["acm", ["ACM_main"], ["ACM_"], ["ACM_"], ["ACM_"], ["misc", "ammo"]],
    ["ace", ["ace_main"], ["ace_"], ["ace_", "ace3_"], ["ace_", "ace3_"], ["misc", "ammo"]]
];

FLO_StoreSupportRejectPatterns = [
    "admin",
    "arsenal",
    "base",
    "curator",
    "deprecated",
    "debug",
    "dummy",
    "helper",
    "module",
    "placeholder",
    "programmer",
    "rack",
    "test",
    "vehicle",
    "zeus"
];

FLO_StoreSupportCatalogItems = [
    ["FirstAidKit", "gear", "misc"],
    ["Medikit", "gear", "misc"],

    ["ACE_adenosine", "gear", "misc"],
    ["ACE_atropine", "gear", "misc"],
    ["ACE_bloodIV", "gear", "misc"],
    ["ACE_bloodIV_250", "gear", "misc"],
    ["ACE_bloodIV_500", "gear", "misc"],
    ["ACE_bodyBag", "gear", "misc"],
    ["ACE_EarPlugs", "gear", "misc"],
    ["ACE_elasticBandage", "gear", "misc"],
    ["ACE_epinephrine", "gear", "misc"],
    ["ACE_fieldDressing", "gear", "misc"],
    ["ACE_morphine", "gear", "misc"],
    ["ACE_packingBandage", "gear", "misc"],
    ["ACE_personalAidKit", "gear", "misc"],
    ["ACE_plasmaIV", "gear", "misc"],
    ["ACE_plasmaIV_250", "gear", "misc"],
    ["ACE_plasmaIV_500", "gear", "misc"],
    ["ACE_quikclot", "gear", "misc"],
    ["ACE_salineIV", "gear", "misc"],
    ["ACE_salineIV_250", "gear", "misc"],
    ["ACE_salineIV_500", "gear", "misc"],
    ["ACE_splint", "gear", "misc"],
    ["ACE_surgicalKit", "gear", "misc"],
    ["ACE_tourniquet", "gear", "misc"],

    ["ACRE_PRC343", "gear", "misc"],
    ["ACRE_PRC148", "gear", "misc"],
    ["ACRE_PRC152", "gear", "misc"],
    ["ACRE_PRC77", "gear", "misc"],
    ["ACRE_PRC117F", "gear", "misc"],
    ["ACRE_SEM52SL", "gear", "misc"],
    ["ACRE_SEM70", "gear", "misc"],
    ["ACRE_BF888S", "gear", "misc"],
    ["ACRE_VHF30108", "gear", "backpacks"],
    ["ACRE_VHF30108SPIKE", "gear", "backpacks"],
    ["ACRE_VHF30108MAST", "gear", "backpacks"],
    ["ACRE_VHF30108MASTB", "gear", "backpacks"],

    ["TFAR_anprc152", "gear", "misc"],
    ["TFAR_fadak", "gear", "misc"],
    ["TFAR_microdagr", "gear", "misc"],
    ["TFAR_pnr1000a", "gear", "misc"],
    ["TFAR_rf7800str", "gear", "misc"],
    ["tf_anprc152", "gear", "misc"],
    ["tf_fadak", "gear", "misc"],
    ["tf_microdagr", "gear", "misc"],
    ["tf_pnr1000a", "gear", "misc"],
    ["tf_rf7800str", "gear", "misc"],
    ["TFAR_anprc155", "gear", "backpacks"],
    ["TFAR_anprc155_coyote", "gear", "backpacks"],
    ["TFAR_mr3000", "gear", "backpacks"],
    ["TFAR_mr3000_bwmod", "gear", "backpacks"],
    ["TFAR_mr3000_bwmod_tropen", "gear", "backpacks"],
    ["TFAR_mr3000_multicam", "gear", "backpacks"],
    ["TFAR_mr3000_rhs", "gear", "backpacks"],
    ["TFAR_rt1523g", "gear", "backpacks"],
    ["TFAR_rt1523g_big", "gear", "backpacks"],
    ["TFAR_rt1523g_black", "gear", "backpacks"],
    ["TFAR_rt1523g_fabric", "gear", "backpacks"],
    ["TFAR_rt1523g_green", "gear", "backpacks"],
    ["TFAR_rt1523g_sage", "gear", "backpacks"],
    ["tf_anprc155", "gear", "backpacks"],
    ["tf_anprc155_coyote", "gear", "backpacks"],
    ["tf_mr3000", "gear", "backpacks"],
    ["tf_mr3000_bwmod", "gear", "backpacks"],
    ["tf_mr3000_bwmod_tropen", "gear", "backpacks"],
    ["tf_mr3000_multicam", "gear", "backpacks"],
    ["tf_mr3000_rhs", "gear", "backpacks"],
    ["tf_rt1523g", "gear", "backpacks"],
    ["tf_rt1523g_big", "gear", "backpacks"],
    ["tf_rt1523g_black", "gear", "backpacks"],
    ["tf_rt1523g_fabric", "gear", "backpacks"],
    ["tf_rt1523g_green", "gear", "backpacks"],
    ["tf_rt1523g_sage", "gear", "backpacks"],

    ["kat_aatKit", "gear", "misc"],
    ["kat_accuvac", "gear", "misc"],
    ["kat_AED", "gear", "misc"],
    ["kat_AFAK", "gear", "misc"],
    ["kat_amiodarone", "gear", "misc"],
    ["kat_atropine", "gear", "misc"],
    ["kat_BVM", "gear", "misc"],
    ["kat_Caffeine", "gear", "misc"],
    ["kat_Carbonate", "gear", "misc"],
    ["kat_chestSeal", "gear", "misc"],
    ["kat_clamp", "gear", "misc"],
    ["kat_crossPanel", "gear", "misc"],
    ["kat_epinephrine", "gear", "misc"],
    ["kat_etomidate", "gear", "misc"],
    ["kat_fentanyl", "gear", "misc"],
    ["kat_flumazenil", "gear", "misc"],
    ["kat_guedel", "gear", "misc"],
    ["kat_IO_FAST", "gear", "misc"],
    ["kat_IV_16", "gear", "misc"],
    ["kat_ketamine", "gear", "misc"],
    ["kat_larynx", "gear", "misc"],
    ["kat_lidocaine", "gear", "misc"],
    ["kat_lorazepam", "gear", "misc"],
    ["kat_MFAK", "gear", "misc"],
    ["kat_morphine", "gear", "misc"],
    ["kat_nalbuphine", "gear", "misc"],
    ["kat_naloxone", "gear", "misc"],
    ["kat_nitroglycerin", "gear", "misc"],
    ["kat_norepinephrine", "gear", "misc"],
    ["kat_oxygenTank_150_Item", "gear", "misc"],
    ["kat_oxygenTank_300_Item", "gear", "misc"],
    ["kat_oxygenTank_450_Item", "gear", "misc"],
    ["kat_Painkiller", "gear", "misc"],
    ["kat_Penthrox", "gear", "misc"],
    ["kat_phenylephrine", "gear", "misc"],
    ["kat_plate", "gear", "misc"],
    ["kat_Pressurebandage", "gear", "misc"],
    ["kat_Pulseoximeter", "gear", "misc"],
    ["kat_retractor", "gear", "misc"],
    ["kat_scalpel", "gear", "misc"],
    ["kat_stethoscope", "gear", "misc"],
    ["kat_suction", "gear", "misc"],
    ["kat_TXA", "gear", "misc"],
    ["kat_vacuum", "gear", "misc"],
    ["kat_X_AED", "gear", "misc"],

    ["ACM_FreshBloodBag_250", "gear", "misc"],
    ["ACM_FreshBloodBag_500", "gear", "misc"],
    ["ACM_FreshBloodBag_1000", "gear", "misc"],
    ["ACM_GasMaskFilter", "gear", "misc"],
    ["ACM_IGel", "gear", "misc"],
    ["ACM_IO_EZ", "gear", "misc"],
    ["ACM_IO_FAST", "gear", "misc"],
    ["ACM_IV_14g", "gear", "misc"],
    ["ACM_IV_16g", "gear", "misc"],
    ["ACM_Lozenge_Fentanyl", "gear", "misc"],
    ["ACM_NCDKit", "gear", "misc"],
    ["ACM_NPA", "gear", "misc"],
    ["ACM_OPA", "gear", "misc"],
    ["ACM_OxygenTank_425_Empty", "gear", "misc"],
    ["ACM_Paracetamol_SinglePack", "gear", "misc"],
    ["ACM_PocketBVM", "gear", "misc"],
    ["ACM_PressureBandage", "gear", "misc"],
    ["ACM_PressureCuff", "gear", "misc"],
    ["ACM_PulseOximeter", "gear", "misc"],
    ["ACM_SAMSplint", "gear", "misc"],
    ["ACM_Spray_Naloxone", "gear", "misc"],
    ["ACM_Stethoscope", "gear", "misc"],
    ["ACM_SuctionBag", "gear", "misc"],
    ["ACM_Syringe_1", "gear", "misc"],
    ["ACM_Syringe_3", "gear", "misc"],
    ["ACM_Syringe_5", "gear", "misc"],
    ["ACM_Syringe_10", "gear", "misc"],
    ["ACM_ThoracostomyKit", "gear", "misc"],
    ["ACM_Vial_Adenosine", "gear", "misc"],
    ["ACM_Vial_Amiodarone", "gear", "misc"],
    ["ACM_Vial_Atropine", "gear", "misc"],
    ["ACM_Vial_CalciumChloride", "gear", "misc"],
    ["ACM_Vial_Epinephrine", "gear", "misc"],
    ["ACM_Vial_Ertapenem", "gear", "misc"],
    ["ACM_Vial_Esmolol", "gear", "misc"],
    ["ACM_Vial_Fentanyl", "gear", "misc"],
    ["ACM_Vial_Ketamine", "gear", "misc"],
    ["ACM_Vial_Lidocaine", "gear", "misc"],
    ["ACM_Vial_Naloxone", "gear", "misc"],
    ["ACM_Vial_Norepinephrine", "gear", "misc"],
    ["ACM_Vial_Phenylephrine", "gear", "misc"],
    ["ACM_Vial_TXA", "gear", "misc"],

    ["ItemGPS", "gear", "misc"],
    ["ItemcTab", "gear", "misc"],
    ["ItemAndroid", "gear", "misc"],
    ["ItemcTabHCam", "gear", "misc"],
    ["ItemMicroDAGR", "gear", "misc"],
    ["ItemcTabMisc", "gear", "misc"],
    ["ItemAndroidMisc", "gear", "misc"],
    ["ItemMicroDAGRMisc", "gear", "misc"],
    ["ItemcTabMISC", "gear", "misc"],
    ["ItemAndroidMISC", "gear", "misc"],
    ["ItemMicroDAGRMISC", "gear", "misc"]
];
