class Command {
    file = "\z\foof\addons\main\functions\command";

    class commandAddWebEventHandler {};
    class commandBroadcastSide {};
    class commandBuildFactionOptions {};
    class commandBuildSideSnapshot {};
    class commandCanOpenVoteDialog {};
    class commandClientInit {};
    class commandClientNeedsSnapshot {};
    class commandApplyPlayerRoles {};
    class commandAssignRole {};
    class commandClearRole {};
    class commandClearUidRoles {};
    class commandEnsureInitialVoteWindow {};
    class commandExpireVoteWindow {};
    class commandHandleVoteUiEvent {};
    class commandInitServer {};
    class commandOpenVoteDialog {};
    class commandPlayerHasAuthority {};
    class commandPostInit { postInit = 1; };
    class commandPreInit { preInit = 1; };
    class commandPruneRoleAssignments {};
    class commandReceiveSnapshot {};
    class commandRequestSnapshot {};
    class commandResolveCommanderVote {};
    class commandResolveFactionVote {};
    class commandRoleCaps {};
    class commandScheduleBroadcastSide {};
    class commandSendSnapshot {};
    class commandSidePlayers {};
    class commandStartVoteWindow {};
    class commandSyncRoleGrants {};
    class commandSyncConnectedPlayer {};
    class commandUpdateVoteDialog {};
    class commandVoteCommander {};
    class commandVoteFaction {};
    class commandWebAction {};
};
